import React, { useEffect, useMemo, useState } from 'react';
import {
  AlertTriangle,
  ShieldAlert,
  ShieldCheck,
  FileText,
  Download,
  RefreshCw,
  Clock,
  Activity
} from 'lucide-react';
import { fetchFileList } from '../services/api';

export default function AlertsReportsPage() {
  const [files, setFiles] = useState([]);
  const [filter, setFilter] = useState('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const loadAlerts = async () => {
    try {
      setLoading(true);
      setError('');

      const data = await fetchFileList();
      setFiles(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error(err);
      setError('Unable to load malware alerts.');
      setFiles([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const alerts = useMemo(() => {
    return files
      .map((file) => {
        const score = Number(file.analysis_result?.risk_score ?? 0);

        let severity = 'low';

        if (score >= 80) {
          severity = 'critical';
        } else if (score >= 60) {
          severity = 'high';
        } else if (score >= 30) {
          severity = 'medium';
        }

        return {
          ...file,
          score,
          severity,
          classification:
            file.analysis_result?.threat_classification || 'Unknown'
        };
      })
      .filter((file) => {
        if (filter === 'all') return file.score >= 30;
        return file.severity === filter;
      })
      .sort((a, b) => b.score - a.score);
  }, [files, filter]);

  const counts = useMemo(() => {
    const normalized = files.map((file) => {
      const score = Number(file.analysis_result?.risk_score ?? 0);

      return {
        score,
        severity:
          score >= 80
            ? 'critical'
            : score >= 60
            ? 'high'
            : score >= 30
            ? 'medium'
            : 'low'
      };
    });

    return {
      critical: normalized.filter((x) => x.severity === 'critical').length,
      high: normalized.filter((x) => x.severity === 'high').length,
      medium: normalized.filter((x) => x.severity === 'medium').length,
      total: normalized.filter((x) => x.score >= 30).length
    };
  }, [files]);

  const generateReport = (file) => {
    const analysis = file.analysis_result || {};
    const yaraResults = file.yara_results || [];

    const report = `
THREATLENS AI - MALWARE SECURITY REPORT
=======================================

FILE INFORMATION
----------------
Filename: ${file.filename || 'Unknown'}
File Size: ${file.file_size || 0} bytes
MD5: ${file.md5_hash || 'N/A'}
SHA-256: ${file.sha256_hash || 'N/A'}
File Type: ${file.file_type || 'N/A'}
Status: ${file.status || 'N/A'}

THREAT ASSESSMENT
-----------------
Classification: ${analysis.threat_classification || 'Unknown'}
Risk Score: ${analysis.risk_score ?? 0}/100
Recommended Action: ${analysis.recommended_action || 'Review required'}

YARA RESULTS
------------
${
  yaraResults.length
    ? yaraResults
        .map(
          (rule, index) =>
            `${index + 1}. ${rule.rule_name || 'Unknown Rule'}
   Severity: ${rule.severity || 'Unknown'}
   Tags: ${(rule.tags || []).join(', ') || 'None'}`
        )
        .join('\n')
    : 'No YARA rule matches detected.'
}

REPORT GENERATED
----------------
${new Date().toLocaleString()}

Generated by ThreatLens AI
Malware Detection & Analytics Platform
`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `${file.filename || 'malware'}_security_report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const severityClass = (severity) => {
    if (severity === 'critical') {
      return 'bg-red-500/10 text-red-400 border-red-500/30';
    }

    if (severity === 'high') {
      return 'bg-orange-500/10 text-orange-400 border-orange-500/30';
    }

    if (severity === 'medium') {
      return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
    }

    return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
  };

  const scoreClass = (score) => {
    if (score >= 80) return 'text-red-400';
    if (score >= 60) return 'text-orange-400';
    if (score >= 30) return 'text-amber-400';
    return 'text-emerald-400';
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-gray-800">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            Alerts & Malware Reports
            <span className="text-xs bg-red-500/10 text-red-400 border border-red-500/30 px-2.5 py-0.5 rounded-full font-mono">
              Member 5
            </span>
          </h1>

          <p className="text-sm text-gray-400 mt-1">
            Monitor suspicious files, high-risk threats and generate security reports.
          </p>
        </div>

        <button
          onClick={loadAlerts}
          className="inline-flex items-center justify-center gap-2 bg-gray-800 hover:bg-gray-700 text-gray-200 px-4 py-2.5 rounded-xl border border-gray-700 text-sm transition-all"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh Alerts
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">

        <div className="bg-[#111827] border border-gray-800 rounded-xl p-5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Active Alerts
            </span>
            <ShieldAlert className="w-5 h-5 text-red-400" />
          </div>

          <div className="text-3xl font-extrabold text-red-400 mt-3">
            {counts.total}
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Risk score ≥ 30
          </p>
        </div>

        <div className="bg-[#111827] border border-gray-800 rounded-xl p-5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Critical
            </span>
            <AlertTriangle className="w-5 h-5 text-red-400" />
          </div>

          <div className="text-3xl font-extrabold text-red-400 mt-3">
            {counts.critical}
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Risk score ≥ 80
          </p>
        </div>

        <div className="bg-[#111827] border border-gray-800 rounded-xl p-5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              High Risk
            </span>
            <Activity className="w-5 h-5 text-orange-400" />
          </div>

          <div className="text-3xl font-extrabold text-orange-400 mt-3">
            {counts.high}
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Risk score 60–79
          </p>
        </div>

        <div className="bg-[#111827] border border-gray-800 rounded-xl p-5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
              Medium Risk
            </span>
            <ShieldCheck className="w-5 h-5 text-amber-400" />
          </div>

          <div className="text-3xl font-extrabold text-amber-400 mt-3">
            {counts.medium}
          </div>

          <p className="text-xs text-gray-500 mt-2">
            Risk score 30–59
          </p>
        </div>

      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2">
        {['all', 'critical', 'high', 'medium'].map((item) => (
          <button
            key={item}
            onClick={() => setFilter(item)}
            className={`px-4 py-2 rounded-lg text-sm font-medium border transition-all ${
              filter === item
                ? 'bg-blue-600/20 text-blue-400 border-blue-500/40'
                : 'bg-gray-900 text-gray-400 border-gray-800 hover:text-gray-200'
            }`}
          >
            {item === 'all'
              ? 'All Alerts'
              : item.charAt(0).toUpperCase() + item.slice(1)}
          </button>
        ))}
      </div>

      {/* Error */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl p-4">
          {error}
        </div>
      )}

      {/* Alert Table */}
      <div className="bg-[#111827] border border-gray-800 rounded-2xl overflow-hidden shadow-xl">

        <div className="px-6 py-5 border-b border-gray-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-red-400" />
            <h2 className="text-lg font-semibold text-white">
              Security Alerts
            </h2>
          </div>

          <span className="text-xs text-gray-400 font-mono">
            {alerts.length} alerts
          </span>
        </div>

        {loading ? (
          <div className="p-10 text-center text-gray-400">
            Loading alerts...
          </div>
        ) : alerts.length === 0 ? (
          <div className="p-10 text-center">
            <ShieldCheck className="w-10 h-10 text-emerald-400 mx-auto mb-3" />
            <p className="text-white font-medium">No alerts found</p>
            <p className="text-gray-500 text-sm mt-1">
              No files match the selected risk level.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-gray-300">

              <thead className="bg-gray-900/60 text-xs text-gray-400 uppercase tracking-wider border-b border-gray-800">
                <tr>
                  <th className="px-6 py-3.5">Filename</th>
                  <th className="px-6 py-3.5">Classification</th>
                  <th className="px-6 py-3.5">Severity</th>
                  <th className="px-6 py-3.5">Risk Score</th>
                  <th className="px-6 py-3.5">Scan Time</th>
                  <th className="px-6 py-3.5 text-right">Report</th>
                </tr>
              </thead>

              <tbody className="divide-y divide-gray-800/60">

                {alerts.map((file) => (
                  <tr
                    key={file.id}
                    className="hover:bg-gray-800/40 transition-colors"
                  >

                    <td className="px-6 py-4">
                      <div className="font-medium text-white">
                        {file.filename}
                      </div>

                      <div className="text-xs text-gray-500 font-mono mt-1">
                        {file.sha256_hash
                          ? `${file.sha256_hash.substring(0, 16)}...`
                          : 'Hash unavailable'}
                      </div>
                    </td>

                    <td className="px-6 py-4">
                      <span className="text-sm text-gray-200">
                        {file.classification}
                      </span>
                    </td>

                    <td className="px-6 py-4">
                      <span
                        className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium border ${severityClass(
                          file.severity
                        )}`}
                      >
                        {file.severity.toUpperCase()}
                      </span>
                    </td>

                    <td className="px-6 py-4">
                      <span
                        className={`font-bold font-mono ${scoreClass(
                          file.score
                        )}`}
                      >
                        {file.score}/100
                      </span>
                    </td>

                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2 text-xs text-gray-400">
                        <Clock className="w-3.5 h-3.5" />
                        {file.uploaded_at
                          ? new Date(file.uploaded_at).toLocaleString()
                          : 'N/A'}
                      </div>
                    </td>

                    <td className="px-6 py-4 text-right">
                      <button
                        onClick={() => generateReport(file)}
                        className="inline-flex items-center gap-2 text-xs font-medium text-blue-400 hover:text-blue-300 bg-blue-950/40 border border-blue-800/60 px-3 py-1.5 rounded-lg transition-all"
                      >
                        <Download className="w-3.5 h-3.5" />
                        Generate
                      </button>
                    </td>

                  </tr>
                ))}

              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Report Information */}
      <div className="bg-[#111827] border border-gray-800 rounded-2xl p-6">
        <div className="flex items-center gap-3 mb-3">
          <FileText className="w-5 h-5 text-blue-400" />
          <h2 className="text-lg font-semibold text-white">
            Malware Security Reports
          </h2>
        </div>

        <p className="text-sm text-gray-400">
          Select <strong className="text-gray-200">Generate</strong> on an alert
          to create a security report containing file information, SHA-256
          hash, malware classification, risk score, recommended action and
          YARA rule results.
        </p>
      </div>

    </div>
  );
}