"""
ThreatLens AI - Milestone 3
Member 1: Threat Prediction Report Generator

Generates a structured security report from the output
of the behavioral analysis and threat prediction engines.
"""

from datetime import datetime, timezone
from typing import Any, Dict


def generate_threat_report(
    filename: str,
    sha256_hash: str,
    threat_prediction: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Generate a structured threat prediction report.

    Parameters
    ----------
    filename:
        Name of the analyzed file.

    sha256_hash:
        SHA-256 hash of the analyzed file.

    threat_prediction:
        Output generated by predict_threat().
    """

    behaviors = threat_prediction.get(
        "detected_behaviors",
        []
    )

    # --------------------------------------------------------
    # Count behavior severities
    # --------------------------------------------------------

    critical_count = sum(
        1
        for behavior in behaviors
        if behavior.get("severity") == "Critical"
    )

    high_count = sum(
        1
        for behavior in behaviors
        if behavior.get("severity") == "High"
    )

    medium_count = sum(
        1
        for behavior in behaviors
        if behavior.get("severity") == "Medium"
    )

    low_count = sum(
        1
        for behavior in behaviors
        if behavior.get("severity") == "Low"
    )

    # --------------------------------------------------------
    # Build behavioral findings
    # --------------------------------------------------------

    findings = []

    for behavior in behaviors:

        findings.append({
            "behavior": behavior.get(
                "behavior",
                "Unknown"
            ),
            "severity": behavior.get(
                "severity",
                "Unknown"
            ),
            "confidence": behavior.get(
                "confidence",
                0
            ),
            "evidence": behavior.get(
                "evidence",
                []
            ),
            "description": behavior.get(
                "description",
                ""
            ),
        })

    # --------------------------------------------------------
    # Security summary
    # --------------------------------------------------------

    threat_level = threat_prediction.get(
        "threat_level",
        "Unknown"
    )

    threat_category = threat_prediction.get(
        "threat_category",
        "Unknown"
    )

    final_score = threat_prediction.get(
        "final_threat_score",
        0
    )

    ml_prediction = threat_prediction.get(
        "ml_prediction",
        "Unknown"
    )

    ml_confidence = threat_prediction.get(
        "ml_confidence",
        0
    )

    if threat_level == "Critical":
        security_summary = (
            "The analyzed file presents a critical security threat. "
            "Multiple strong indicators or critical behavioral evidence "
            "were identified. Immediate containment and investigation "
            "are recommended."
        )

    elif threat_level == "High":
        security_summary = (
            "The analyzed file presents a high security risk. "
            "Significant malicious indicators were identified and "
            "further investigation is recommended."
        )

    elif threat_level == "Medium":
        security_summary = (
            "The analyzed file presents suspicious activity. "
            "Security review is recommended before allowing the file."
        )

    else:
        security_summary = (
            "No significant malicious behavioral evidence was detected. "
            "The file may be allowed with monitoring."
        )

    # --------------------------------------------------------
    # Final report
    # --------------------------------------------------------

    report = {
        "report_metadata": {
            "generated_at": datetime.now(
                timezone.utc
            ).isoformat(),
            "report_type": "AI Threat Prediction Report",
            "system": "ThreatLens AI",
        },

        "file_information": {
            "filename": filename,
            "sha256_hash": sha256_hash,
        },

        "ml_analysis": {
            "prediction": ml_prediction,
            "confidence": ml_confidence,
        },

        "behavioral_analysis": {
            "behavior_count": len(behaviors),
            "behavior_score": threat_prediction.get(
                "behavior_score",
                0
            ),
            "critical_findings": critical_count,
            "high_findings": high_count,
            "medium_findings": medium_count,
            "low_findings": low_count,
            "findings": findings,
        },

        "threat_assessment": {
            "final_threat_score": final_score,
            "threat_level": threat_level,
            "threat_category": threat_category,
        },

        "response": {
            "recommended_action": threat_prediction.get(
                "recommended_action",
                "Review manually"
            ),
        },

        "security_summary": security_summary,
    }

    return report


# ============================================================
# MANUAL TEST
# ============================================================

if __name__ == "__main__":

    import json

    from behavioral_analysis import analyze_behavior
    from threat_prediction import predict_threat

    # --------------------------------------------------------
    # Generate behavioral result
    # --------------------------------------------------------

    behavioral_result = analyze_behavior(
        suspicious_apis=[
            "Kernel32.dll -> VirtualAlloc",
            "Kernel32.dll -> WriteProcessMemory",
            "Kernel32.dll -> CreateRemoteThread",
            "Urlmon.dll -> URLDownloadToFileA",
        ],

        extracted_strings=[
            "powershell.exe -ExecutionPolicy Bypass -W Hidden",
            "cmd.exe /c reg add "
            "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        ],

        network_indicators={
            "urls": [
                "http://malicious-site.com/payload.ps1"
            ],
            "ips": [
                "185.220.101.5"
            ],
        },

        pe_headers={
            "entry_point": "0x00401000",
            "number_of_sections": 5,
        },

        yara_results=[
            {
                "rule_name": "Suspicious_PowerShell_Execution",
                "severity": "high",
            }
        ],
    )

    # --------------------------------------------------------
    # Generate threat prediction
    # --------------------------------------------------------

    threat_prediction = predict_threat(
        ml_prediction="Malware",
        ml_confidence=0.948,
        behavioral_result=behavioral_result,
    )

    # --------------------------------------------------------
    # Generate report
    # --------------------------------------------------------

    report = generate_threat_report(
        filename="invoice.exe",
        sha256_hash=(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        ),
        threat_prediction=threat_prediction,
    )

    print(
        json.dumps(
            report,
            indent=4
        )
    )